[project]
name = "kb-assist"
version = "0.1.0"
description = "Personal knowledge base assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=0.2.0",
    "langchain>=0.3.3",
    "pygit2>=1.15.1",
]
